### ISSUE TITLE
Dependencies of this project

### ISSUE THREAD

**Issue by wolf943134497** [HKUST-Aerial-Robotics/Omni-swarm#1]
Hi @xuhao1  thanks for your works and sharing the code.

what are the dependencies of this project?  I got some errors when I compile the project.
error1:  bspline/Bspline.h: No such file or directory
error2:  tensorrt_generic.h:22:5: error: ‘Logger’ does not name a type
error3:  faiss/IndexFlat.h: No such file or directory, faiss required?
I want to test the code on one robot,  maybe vins-fisheye + swarm-loop is enough? Is there a simple solution for vins-fisheye + loop closure? 
many thanks!

**Comment by xuhao1** [comment]
Hi @wolf943134497 , thanks for your interest in this project, we will release docker for this project later.

**Comment by wolf943134497** [comment]
> Hi @wolf943134497 , thanks for your interest in this project, we will release docker for this project later.

good news!  looking forward for it 

Thanks for your reply and additional work.

**Comment by KillerQueen1024** [comment]
@wolf943134497 请立刻联系我，你仓库里面的 LIO 我已经删除了，请你也删除掉

**Comment by KillerQueen1024** [comment]
@wolf943134497

**Comment by KillerQueen1024** [comment]
@wolf943134497

**Comment by KillerQueen1024** [comment]
@wolf943134497

**Comment by KillerQueen1024** [comment]
@wolf943134497

**Comment by KillerQueen1024** [comment]
@wolf943134497 你好， 我是LIO-wheel-fusion 项目 这个原始仓库的主人，吴新锐。 lio-wheel-fusion工程， 是我们内部项目，因为设计项目保密协议
之前误上传至了github，现原始仓库 lio-wheel-fusion 已经删除， 请您看到此消息后， 删除此 fork 得到的仓库， 谢谢合作！！！！
或者看到此条消息后，尽快联系邮箱  916806487 或者电话 15201978695！！  谢谢合作！！

如有疑问请联系  916806487@sjtu.edu.cn   或者电话致电  15201978695 ，谢谢合作！

**Comment by KillerQueen1024** [comment]
@wolf943134497 你好， 我是LIO-wheel-fusion 项目 这个原始仓库的主人，吴新锐。 lio-wheel-fusion工程， 是我们内部项目，因为设计项目保密协议
之前误上传至了github，现原始仓库 lio-wheel-fusion 已经删除， 请您看到此消息后， 删除此 fork 得到的仓库， 谢谢合作！！！！
或者看到此条消息后，尽快联系邮箱  916806487 或者电话 15201978695！！  谢谢合作！！

如有疑问请联系  916806487@sjtu.edu.cn   或者电话致电  15201978695 ，谢谢合作！

**Comment by XINRUII** [comment]
@wolf943134497 急！！！ 看到这条消息后可以立刻联系我吗，因为您仓库下的工程涉及保密协议，请您立刻联系我 [916806487@sjtu.edu.cn](mailto:916806487@sjtu.edu.cn)，或者去查看仓库 lio-wheel-fusion 工程的 pull request，谢谢！！

 Could you please contact me immediately after seeing this message? Or check the pull request of lio-wheel-fusion project under your warehouse, thank you!!
