### ISSUE TITLE
Cannot find out graphviz/cgraph.h in swarm_localization

### ISSUE THREAD

**Issue by dssdyx** [HKUST-Aerial-Robotics/Omni-swarm#11]
Hi, this is an amazing project of swarm global localization. I want to learn from your project. But when I compile source code, there is a graphviz/cgraph.h file not found. I read the code, and find this module used to generate cgraph. What is the function of cgraph and how to add this module?

**Comment by xuhao1** [comment]
On ubuntu: 
```
sudo apt install graphviz-dev
```

**Comment by dssdyx** [comment]
> On ubuntu:
> 
> ```
> sudo apt install graphviz-dev
> ```

THK for your reply！
