### ISSUE TITLE
数据集 dataset 

### ISSUE THREAD

**Issue by lu-minous** [HKUST-Aerial-Robotics/Omni-swarm#2]
你好，很棒的工作！

我正在做Vision-Inertial-UWB定位算法，你的数据集用来测试非常合适，但是dropbox里的数据集文件夹是空的，能上传一下吗？
万分感谢！！

**Comment by xuhao1** [comment]
Sure, I will upload this weekend.

**Comment by CAIQIUJI** [comment]
Your dataset is always unable to continue downloading until the end. I have asked my friends to help me try it out. May I ask if there is a problem with the upload or with the dropbox?
